window.COLOR_PRESETS = {

  skin: [
    { id: "skin_porcelain", name: "Porcelain", hex: "#F8DED2" },
    { id: "skin_ivory", name: "Ivory", hex: "#F3D2BF" },
    { id: "skin_pale_peach", name: "Pale Peach", hex: "#F6CDB7" },
    { id: "skin_soft_beige", name: "Soft Beige", hex: "#EFC3A8" },
    { id: "skin_warm_ivory", name: "Warm Ivory", hex: "#F0C7A6" },
    { id: "skin_blush_beige", name: "Blush Beige", hex: "#E8B89F" },
    { id: "skin_peach_beige", name: "Peach Beige", hex: "#E9B394" },
    { id: "skin_light_sand", name: "Light Sand", hex: "#E2B18F" },
    { id: "skin_honey_beige", name: "Honey Beige", hex: "#DDA984" },
    { id: "skin_warm_sand", name: "Warm Sand", hex: "#D7A17E" },
    { id: "skin_golden_beige", name: "Golden Beige", hex: "#D69A70" },
    { id: "skin_soft_tan", name: "Soft Tan", hex: "#CD956F" },
    { id: "skin_peach_tan", name: "Peach Tan", hex: "#C98B69" },
    { id: "skin_golden_tan", name: "Golden Tan", hex: "#C58A5F" },
    { id: "skin_warm_tan", name: "Warm Tan", hex: "#BC805D" },
    { id: "skin_caramel", name: "Caramel", hex: "#B97950" },
    { id: "skin_honey_brown", name: "Honey Brown", hex: "#AD704C" },
    { id: "skin_amber_brown", name: "Amber Brown", hex: "#A96B45" },
    { id: "skin_warm_bronze", name: "Warm Bronze", hex: "#9F6545" },
    { id: "skin_bronze_brown", name: "Bronze Brown", hex: "#955B3F" },
    { id: "skin_chestnut", name: "Chestnut", hex: "#8D563D" },
    { id: "skin_cinnamon_brown", name: "Cinnamon Brown", hex: "#865037" },
    { id: "skin_warm_cocoa", name: "Warm Cocoa", hex: "#7A4935" },
    { id: "skin_mocha", name: "Mocha", hex: "#704332" },
    { id: "skin_deep_caramel", name: "Deep Caramel", hex: "#68402F" },
    { id: "skin_walnut_brown", name: "Walnut Brown", hex: "#603B2D" },
    { id: "skin_deep_cocoa", name: "Deep Cocoa", hex: "#55352A" },
    { id: "skin_espresso_brown", name: "Espresso Brown", hex: "#493027" },
    { id: "skin_dark_chocolate", name: "Dark Chocolate", hex: "#3D2923" },
    { id: "skin_deep_espresso", name: "Deep Espresso", hex: "#31221E" },
    { id: "skin_red_ish", name: "Red-ish", hex: "#C94C4C" },
    { id: "skin_orange_ish", name: "Orange-ish", hex: "#D9783D" },
    { id: "skin_yellow_ish", name: "Yellow-ish", hex: "#D9C84A" },
    { id: "skin_lime_ish", name: "Lime-ish", hex: "#9ACB4B" },
    { id: "skin_green_ish", name: "Green-ish", hex: "#52A96B" },
    { id: "skin_mint_ish", name: "Mint-ish", hex: "#65C9A5" },
    { id: "skin_teal_ish", name: "Teal-ish", hex: "#429C9C" },
    { id: "skin_cyan_ish", name: "Cyan-ish", hex: "#4AB8C7" },
    { id: "skin_blue_ish", name: "Blue-ish", hex: "#527FC4" },
    { id: "skin_indigo_ish", name: "Indigo-ish", hex: "#5D62A8" },
    { id: "skin_purple_ish", name: "Purple-ish", hex: "#8660AD" },
    { id: "skin_violet_ish", name: "Violet-ish", hex: "#A15CA5" },
    { id: "skin_pink_ish", name: "Pink-ish", hex: "#D86F9A" },
    { id: "skin_gray_ish", name: "Gray-ish", hex: "#8B8583" },
    { id: "skin_white_ish", name: "White-ish", hex: "#E8E2DF" }
  ],


  eyes: [
    { id: "eye_pale_blue", name: "Pale Blue", hex: "#A9C7D8" },
    { id: "eye_ice_blue", name: "Ice Blue", hex: "#B8D8E8" },
    { id: "eye_sky_blue", name: "Sky Blue", hex: "#78AFC7" },
    { id: "eye_steel_blue", name: "Steel Blue", hex: "#6F8FA6" },
    { id: "eye_gray_blue", name: "Gray Blue", hex: "#7E99A8" },
    { id: "eye_deep_blue", name: "Deep Blue", hex: "#476F91" },
    { id: "eye_blue_gray", name: "Blue Gray", hex: "#6F8792" },
    { id: "eye_silver_gray", name: "Silver Gray", hex: "#A3A6A4" },
    { id: "eye_cool_gray", name: "Cool Gray", hex: "#858D8C" },
    { id: "eye_dark_gray", name: "Dark Gray", hex: "#5F6867" },
    { id: "eye_pale_green", name: "Pale Green", hex: "#A8B88A" },
    { id: "eye_sage_green", name: "Sage Green", hex: "#899B72" },
    { id: "eye_olive_green", name: "Olive Green", hex: "#74804E" },
    { id: "eye_moss_green", name: "Moss Green", hex: "#687445" },
    { id: "eye_forest_green", name: "Forest Green", hex: "#4D6543" },
    { id: "eye_green_hazel", name: "Green Hazel", hex: "#7D814E" },
    { id: "eye_light_hazel", name: "Light Hazel", hex: "#A58A57" },
    { id: "eye_golden_hazel", name: "Golden Hazel", hex: "#A47C3D" },
    { id: "eye_olive_hazel", name: "Olive Hazel", hex: "#81713F" },
    { id: "eye_brown_hazel", name: "Brown Hazel", hex: "#80603E" },
    { id: "eye_amber", name: "Amber", hex: "#B77A29" },
    { id: "eye_golden_amber", name: "Golden Amber", hex: "#C58B35" },
    { id: "eye_honey_brown", name: "Honey Brown", hex: "#9B6B3B" },
    { id: "eye_light_brown", name: "Light Brown", hex: "#8B6548" },
    { id: "eye_warm_brown", name: "Warm Brown", hex: "#745039" },
    { id: "eye_chestnut_brown", name: "Chestnut Brown", hex: "#684633" },
    { id: "eye_dark_brown", name: "Dark Brown", hex: "#50382D" },
    { id: "eye_chocolate_brown", name: "Chocolate Brown", hex: "#453128" },
    { id: "eye_espresso_brown", name: "Espresso Brown", hex: "#352721" },
    { id: "eye_near_black_brown", name: "Near-Black Brown", hex: "#29221F" },
    { id: "eye_red_ish", name: "Red-ish", hex: "#C94C55" },
    { id: "eye_orange_ish", name: "Orange-ish", hex: "#D77A3D" },
    { id: "eye_yellow_ish", name: "Yellow-ish", hex: "#D8C84D" },
    { id: "eye_lime_ish", name: "Lime-ish", hex: "#9BCB50" },
    { id: "eye_green_ish", name: "Green-ish", hex: "#45A76C" },
    { id: "eye_mint_ish", name: "Mint-ish", hex: "#63C9A6" },
    { id: "eye_teal_ish", name: "Teal-ish", hex: "#3D9F9B" },
    { id: "eye_cyan_ish", name: "Cyan-ish", hex: "#45BCCC" },
    { id: "eye_blue_ish", name: "Blue-ish", hex: "#4F78D0" },
    { id: "eye_indigo_ish", name: "Indigo-ish", hex: "#5658A9" },
    { id: "eye_purple_ish", name: "Purple-ish", hex: "#805CB4" },
    { id: "eye_violet_ish", name: "Violet-ish", hex: "#A35FC1" },
    { id: "eye_pink_ish", name: "Pink-ish", hex: "#D66FAD" },
    { id: "eye_silver_ish", name: "Silver-ish", hex: "#B9BEC4" },
    { id: "eye_black_ish", name: "Black-ish", hex: "#24242A" }
  ],


  hair: [
    { id: "hair_platinum_blonde", name: "Platinum Blonde", hex: "#E8E2D4" },
    { id: "hair_pale_blonde", name: "Pale Blonde", hex: "#E6D7B8" },
    { id: "hair_champagne_blonde", name: "Champagne Blonde", hex: "#DDC8A2" },
    { id: "hair_ash_blonde", name: "Ash Blonde", hex: "#C9B99A" },
    { id: "hair_beige_blonde", name: "Beige Blonde", hex: "#D2B995" },
    { id: "hair_golden_blonde", name: "Golden Blonde", hex: "#D8B56D" },
    { id: "hair_honey_blonde", name: "Honey Blonde", hex: "#CFA15D" },
    { id: "hair_dark_blonde", name: "Dark Blonde", hex: "#B08B5D" },
    { id: "hair_strawberry_blonde", name: "Strawberry Blonde", hex: "#C98F6B" },
    { id: "hair_light_auburn", name: "Light Auburn", hex: "#B87552" },
    { id: "hair_copper", name: "Copper", hex: "#B8613D" },
    { id: "hair_ginger", name: "Ginger", hex: "#A95632" },
    { id: "hair_auburn", name: "Auburn", hex: "#8D4935" },
    { id: "hair_deep_auburn", name: "Deep Auburn", hex: "#713A2E" },
    { id: "hair_light_brown", name: "Light Brown", hex: "#A17B5A" },
    { id: "hair_golden_brown", name: "Golden Brown", hex: "#8F6845" },
    { id: "hair_caramel_brown", name: "Caramel Brown", hex: "#8B6043" },
    { id: "hair_chestnut_brown", name: "Chestnut Brown", hex: "#79513B" },
    { id: "hair_warm_brown", name: "Warm Brown", hex: "#684535" },
    { id: "hair_ash_brown", name: "Ash Brown", hex: "#66594F" },
    { id: "hair_medium_brown", name: "Medium Brown", hex: "#5C4539" },
    { id: "hair_chocolate_brown", name: "Chocolate Brown", hex: "#50372D" },
    { id: "hair_dark_chocolate", name: "Dark Chocolate", hex: "#422F29" },
    { id: "hair_espresso_brown", name: "Espresso Brown", hex: "#342823" },
    { id: "hair_soft_black", name: "Soft Black", hex: "#292624" },
    { id: "hair_natural_black", name: "Natural Black", hex: "#201F1E" },
    { id: "hair_blue_black", name: "Blue Black", hex: "#1D2025" },
    { id: "hair_silver_gray", name: "Silver Gray", hex: "#AAA8A3" },
    { id: "hair_ash_gray", name: "Ash Gray", hex: "#85837F" },
    { id: "hair_white_gray", name: "White Gray", hex: "#D8D5CE" },
    { id: "hair_red_ish", name: "Red-ish", hex: "#C74B55" },
    { id: "hair_orange_ish", name: "Orange-ish", hex: "#D7773F" },
    { id: "hair_yellow_ish", name: "Yellow-ish", hex: "#D7BE45" },
    { id: "hair_lime_ish", name: "Lime-ish", hex: "#9FC84A" },
    { id: "hair_green_ish", name: "Green-ish", hex: "#4EA36A" },
    { id: "hair_mint_ish", name: "Mint-ish", hex: "#67C7A5" },
    { id: "hair_teal_ish", name: "Teal-ish", hex: "#3E9898" },
    { id: "hair_cyan_ish", name: "Cyan-ish", hex: "#49B8C9" },
    { id: "hair_blue_ish", name: "Blue-ish", hex: "#5278C5" },
    { id: "hair_indigo_ish", name: "Indigo-ish", hex: "#5E5FA9" },
    { id: "hair_purple_ish", name: "Purple-ish", hex: "#855DAF" },
    { id: "hair_violet_ish", name: "Violet-ish", hex: "#A35FB4" },
    { id: "hair_pink_ish", name: "Pink-ish", hex: "#D56F9E" },
    { id: "hair_silver_ish", name: "Silver-ish", hex: "#BAB8C1" },
    { id: "hair_black_ish", name: "Black-ish", hex: "#25242B" }
  ]

};
